# Required
version: 2

build:
<<<<<<< HEAD
    tools:
        python: "3.9"
=======
   os: "ubuntu-20.04"
   tools:
      python: "3.9"
>>>>>>> ab74205 (Fixing stuff for rtd)

# Build documentation in the docs/ directory with Sphinx
sphinx:
<<<<<<< HEAD
    configuration: docs/source/conf.py
=======
   configuration: docs/source/conf.py
>>>>>>> ab74205 (Fixing stuff for rtd)

# If using Sphinx, optionally build your docs in additional formats such as PDF
# formats:
#    - pdf

# Optionally declare the Python requirements required to build your docs
python:
<<<<<<< HEAD
    install:
    - requirements: requirements.txt
=======
   install:
   - requirements: requirements.txt
   - method: pip
     path: .
>>>>>>> ab74205 (Fixing stuff for rtd)
