# Camera specification file for the DFK23UP031 camera. You may copy and modify this file
# to implement specification files for your own cameras

# This file contains camera-specific options, according to the output of v4l2-ctl -D -l
# -d <device number>. Use this command to make your own camera config files.

name = "DFK 23UP031"

[capabilities]

[capabilities.brightness]
min = 0
max = 4095
step = 1
default = 168

[capabilities.gain]
min = 4
max = 63
step = 1
default = 4

[capabilities.exposure_absolute]
min = 1
max = 300000
step = 1
default = 333
