# Camera specification file for the Logitech C525 webcam, which was the main camera used
# for testing pyCRT. This should serve as an example configuration file for other
# cameras.

# This file contains camera-specific 


